name: retag
author: andriih@backbase.com
description: retag
inputs:
  working-directory-path:
    description: 'Path relative to the repository root, in which commands should be executed.'
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        node index.js
      env:
        WORKING_DIRECTORY_PATH: ${{ github.workspace }}